# url: "https://gmonet.github.io/"
# plugins:
#   - jekyll-seo-tag
#   - jekyll-sitemap
#   - jekyll-remote-theme
# remote_theme: BDHU/minimalist

title: Geoffrey Monet
logo: /assets/images/mainphoto.png
email: geoffrey.monet@ens.fr
domain: gmonet.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://gmonet.github.io  # the base hostname and protocol for your site, e.g. http://example.com

blank_title: true
favicon: true
lsi: false
safe: true
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

description: ""
show_downloads: false
google_analytics: 
remote_theme: BDHU/minimalist
color-scheme: light
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

sidebar:
  - name: CV
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16"><g fill="currentColor"><path d="M4 0h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2zm5.5 1.5v2a1 1 0 0 0 1 1h2l-3-3z"/></g></svg>
    link: /cv.pdf
  - name: Google Scholar
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path d="M5.242 13.769L0 9.5L12 0l12 9.5l-5.242 4.269C17.548 11.249 14.978 9.5 12 9.5c-2.977 0-5.548 1.748-6.758 4.269zM12 10a7 7 0 1 0 0 14a7 7 0 0 0 0-14z" fill="currentColor"/></svg>
    link: https://scholar.google.com/citations?user=zR6afi8AAAAJ